### ISSUE TITLE
"use of closed network connection" errror returned after Close() called

### ISSUE THREAD

**Issue by guo1017138** [coredhcp/coredhcp#103]
Hi experts,

I know this is expected by current and I can ignore this error in my main function. However, it is really noisy that this log will always get printed. This log get printed by coredhcp and I hope we can ignore this expected error and not print it.

[2020-05-09T09:42:19+08:00]  INFO server: Error reading from connection: read udp 0.0.0.0:67: raw-read udp 0.0.0.0:67: use of closed network connection

I have a private fix for this in my forked repo, if you think this fix is reasonable, I can create a pull request to here. Please suggest.
https://github.com/guo1017138/coredhcp/commit/2c39480eeb75844608a6259ba7d69c7c113929fc

**Comment by insomniacslk** [comment]
I'm not sure that's the proper fix, but if you can help me reproduce the issue I'll be happy to look into it

**Comment by guo1017138** [comment]
Hi @insomniacslk , you are correct, my solution just hide the error instead of fix it.
To reproduce it, just replace the end of main function of file https://github.com/coredhcp/coredhcp/blob/master/cmds/coredhcp/main.go to the following will be OK.

	// start server
	srv, err := server.Start(config)
	if err != nil {
		log.Fatal(err)
	}
	go func() {
		if err := srv.Wait(); err != nil {
			log.Print(err)
		}
	}()
	// Serve 10 seconds
	time.Sleep(10 * time.Second)
	// I need to stop dhcp server and continue to other tasks without exit
	srv.Close()
	// wait 5 second to simulate other tasks after dhcp close
	time.Sleep(5 * time.Second)

And the following is the sample output(partial) for the changed main function:

    time="2020-05-11T08:53:01+08:00" level=info msg="Starting DHCPv4 server" prefix=server
    time="2020-05-11T08:53:01+08:00" level=info msg="Listen 0.0.0.0:67" prefix=server
    time="2020-05-11T08:53:11+08:00" level=info msg="Error reading from connection: read udp 0.0.0.0:67: raw-read udp 0.0.0.0:67: use of closed network connection" prefix=server
    time="2020-05-11T08:53:11+08:00" level=info msg="read udp 0.0.0.0:67: raw-read udp 0.0.0.0:67: use of closed network connection" prefix=main
    Process exiting with code: 0

The root cause is simple, the Close() function is to close the listener directly while the for loop in listener.Serve() function still running until it trying to read a closed connection and return error. To fix it, need to find out a way to stop for loop before close conn.

**Comment by Natolumin** [comment]
in go 1.16 we may finally have a fix for this: https://golang.org/doc/go1.16#net
>  The case of I/O on a closed network connection, or I/O on a network connection that is closed before any of the I/O completes, can now be detected using the new ErrClosed error. A typical use would be errors.Is(err, net.ErrClosed). In earlier releases the only way to reliably detect this case was to match the string returned by the Error method with "use of closed network connection".

**Comment by insomniacslk** [comment]
Awesome! With that (and other things like go:embed) I think we can start moving to Go 1.16
