### ISSUE TITLE
Listen on a specific interface

### ISSUE THREAD

**Issue by shellwhale** [coredhcp/coredhcp#105]
Is there a way to force the server to listen to a specific interface ? I'm not seeing anything about this in the README.MD and example files

**Comment by Natolumin** [comment]
It is indeed not in the readme, we should probably add it. But there is an example in the example config:
https://github.com/coredhcp/coredhcp/blob/1d46fd693e093e2e983a9c59973be4415ed9ed87/cmds/coredhcp/config.yml.example#L5

The general syntax is that you add `%<iface>` after the address, before the port: `<address>@<interface>:<port>`
You can also omit the address and/or the port to listen on wildcard on the default port on an interface:
```
listen: %eno1
```
Will listen on the wildcard address on the default port (for the protocol, different for v4 or v6) on that interface

**Comment by insomniacslk** [comment]
I'll add that line to the README

**Comment by insomniacslk** [comment]
we have actually updated the example file and reinforced the wording to point users to the example file

**Comment by MalteJ** [comment]
How can a plugin detect the interface and its IP address, a DHCP request is received via?
The dhcpv4 object is quite empty:
```
INFO plugins/relay: received DHCPv4 packet: DHCPv4 Message
  opcode: BootRequest
  hwtype: Ethernet
  hopcount: 0
  transaction ID: 0x3b3f5e7b
  num seconds: 0
  flags: Unicast (0x00)
  client IP: 0.0.0.0
  your IP: 0.0.0.0
  server IP: 0.0.0.0
  gateway IP: 0.0.0.0
  client MAC: 3a:c7:a1:32:ec:ae
  server hostname:
  bootfile name:
  options:
    Host Name: compute-1
    DHCP Message Type: DISCOVER
    Parameter Request List: Subnet Mask, Time Offset, Domain Name Server, Host Name, Domain Name, Interface MTU, Broadcast Address, NTP Servers, NetBIOS over TCP/IP Name Server, NetBIOS over TCP/IP Scope, DNS Domain Search List, Classless Static Route
```

**Comment by insomniacslk** [comment]
That information is not exposed to the plugins, but it's visible to the listeners, that embed a `net.Interface` object. For example you could print the interface name by adding a
```
log.Printf("Request received on interface %s", l.Name)
```
in [listener6.Serve](https://github.com/coredhcp/coredhcp/blob/master/server/handle.go#L197) and [listener4.Serve](https://github.com/coredhcp/coredhcp/blob/master/server/handle.go#L213)
