### ISSUE TITLE
Broken retracted dep.

### ISSUE THREAD

**Issue by purpleidea** [coredhcp/coredhcp#161]
Unfortunately, most projects have moved to go.mod -- GOPATH and git submodules would have been better.
As a result, someone is using the retract feature here:

https://github.com/u-root/u-root/blob/793a1c12ac7f849185ec7dc927cf8ae9e5ad7bc4/go.mod#L71

This breaks the builds for anyone using this project. See here:

https://github.com/coredhcp/coredhcp/blob/a2552c5c1b7a18344f099014fa6a5386497f7045/go.sum#L264

Please upgrade your deps.

Thanks!

**Comment by dulitz** [comment]
My PR #165 upgrades deps among other things... The deps are very old.
