### ISSUE TITLE
IPv6 address configuration via NDP

### ISSUE THREAD

**Issue by mdlayher** [coredhcp/coredhcp#17]
Hey all, this looks like a pretty neat project! I see you're primarily targeting DHCPv4/6, which makes sense, but was curious if IPv6 address configuration via SLAAC using NDP router advertisements could potentially be in scope for the project as well.

It's been my experience that SLAAC is more common in IPv6 since you don't necessarily have to strictly control which machines get which addresses and etc. It could also be useful even in a simple capacity: sending router advertisements with the "managed" flag to inform clients that they should use DHCPv6 instead of SLAAC.

If these ideas are interesting, I've even got a Go package that should do most of the work! https://github.com/mdlayher/ndp

Let me know what your plans are!

**Comment by insomniacslk** [comment]
> but was curious if IPv6 address configuration via SLAAC using NDP router advertisements could potentially be in scope for the project as well

Absolutely yes!

**Comment by insomniacslk** [comment]
On the plan itself - it's not a hi-pri item at the moment, but if you want to send a few PRs to speed up this side of the development we'd be happy to review them :)

**Comment by mdlayher** [comment]
For sure. I don't have a lot of time for OSS at the moment, but I figured I'd at least get the conversation started.

The tricky thing is figuring out how far you really want to go with it.

As an example, at home, I'm using DHCPv6-PD to get an IPv6 prefix delegated from my ISP, and then I have multiple VLANs that each advertise a /64 for use with SLAAC.  This seems to be the way that most residential providers are doing IPv6, but I imagine there'd a fair amount of inherent complexity in implementing all of that in CoreDHCP.

**Comment by mdlayher** [comment]
I've been thinking about this again for a few days and I suspect it makes more sense to split this out into its own project. The existing functionality is very much DHCP focused and there would be little to no code reuse for NDP. I think I'll give this a go on my own, but if it makes sense for us to have integration points, I'd be happy to talk about that!
