### ISSUE TITLE
Lack of logging for request handling

### ISSUE THREAD

**Issue by DHunte** [coredhcp/coredhcp#30]
Hi,

I seem to have issues using coredhcp but its difficult to tell what the specific problem is as the output of the server simply says "Handling request from 0.0.0.0:68" in an infinite loop whilst i try to connect from another dhcp client. It would be nice to have the server log the results of any "request handling" so it simpler to detect a failure to provide an address and the reason if possible.

**Comment by insomniacslk** [comment]
It's in the plans to improve logging - CoreDHCP is just not ready yet for general use.

Re. the issue itself, if you're using the file plugin, my guess is that the MAC address of your client is not in the leases file

**Comment by DHunte** [comment]
> It's in the plans to improve logging - CoreDHCP is just not ready yet for general use.
> 
> Re. the issue itself, if you're using the file plugin, a common reason is that the MAC address of your client is not in the leases file

This seemed to fix the problem - but is there a feature to auto-add the MAC? Im not sure of the specifics of the behaviour of other DHCP services but im used to plugging a device into the network and it automatically being assigned an IP so having to add the MAC to the list before its assigned seems odd, but im not an expert

**Comment by insomniacslk** [comment]
re. automatically adding MAC addresses - not with the `file` plugin. More plugins need to be implemented, e.g. to provide a DHCP range. The `file` plugin is intentionally only for static assignment of MAC -> IPaddr
