### ISSUE TITLE
Move plugin initialization to main.go

### ISSUE THREAD

**Issue by insomniacslk** [coredhcp/coredhcp#45]
The plugin initialization should not happen in a "magic" `init()` call in the plugins. Rather, the plugins should expose a registration function that does the plugin set-up and returns plugin name and handlers. The framework should handle the rest.

**Comment by Mantic** [comment]
Agreed. Some go linters re-arrange the imports on file save (in VSCode for example), which breaks the intended functionality of the packages. I modified my own copy to simply expose a "Register" function on each plugin so I can call it in the order I like. Plus that allows me to be able to pass in configuration settings at run time to the plugins (in the case I want to grab configs from env variables, databases, etc).
