### ISSUE TITLE
Listening on both multicast and unicast doesn't work (dhcpv6)

### ISSUE THREAD

**Issue by Natolumin** [coredhcp/coredhcp#52]
in #28 and https://github.com/insomniacslk/dhcp/pull/278, connection handling and joining multicast groups was refactored. However, it's not possible (at least in linux) to listen on a non-wildcard unicast address, *and* join multicast groups. If you try now in coredhcp, you'll see the setsockopt call in strace but no traffic received on the multicast address, if there is a `listen` stanza with a unicast address in config.yml. So this: 
```yaml
server6:
    interface: eth0
    listen: 2001:db8:a::2
```
*Only* receives packets for the unicast address and **not** for `ff02::1:2%eth0`, even though the group is joined successfully: (from strace log:)
```
setsockopt(3, SOL_IPV6, MCAST_JOIN_GROUP, {gr_interface=if_nametoindex("eth0"), gr_group={sa_family=AF_INET6, sin6_port=htons(0), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "ff02::1:2", &sin6_addr), sin6_scope_id=0}}, 136)         = 0
```

Left column describes what you listen on, header describes how many multicast groups you join, table describes what traffic you end up receiving

Join > Listen v  | None | One | Multiple
----------------|--------|-------|-----------
**Unicast** | Unicast only | Unicast only | Unicast only
**Multicast** | None | Multicast if it matches the listening address | Multicast, only groups matching the listening address
**Wildcard** | Unicast only | Unicast + Multicast | Unicast + Multicast

Notably, there is no way to listen on a specific unicast address (not wildcard) and receive multicast traffic on the same socket.

I would fix this by implementing a more generic `listen` that can receive multiple addresses:
 * By default, it should listen to both RFC-defined multicast addresses (Ideally it should *not* accept unicast in this mode, but go doesn't let you do that and forces you to bind on `[::]` if you want any multicast, see [1], so we're forced to always bind to wildcard)
 * Adding one (or more) addresses in `listen` opens *separate* sockets to listen on the additional addresses, unicast or multicast without distinction
 * A separate option can be used to disable default multicast addresses (`multicast: no` ?)
 * Remove the `interface` configuration option, to fold it into the specific `listen` stanzas using the standard `addr%iface` notation (mandatory for link-local, recommended for multicast, not necessary for global unicast)

Example:
```yaml
server6: 
    listen: 2001:db8::1 fe80::a%eth0 ff08::1:3%eth1
    multicast: no

server4:
    listen: 0.0.0.0%eth0 192.0.2.1 203.0.113.1
```
note: ipv4 users would need to replace `interface: <iface>` with `listen: 0.0.0.0%<iface>`

I intend to implement this once / if we agree on the details

[1]: Unfortunately, go doesn't let you listen on a specific multicast address and replaces the provided address with the wildcard address in order to be "helpful": [sock_posix.go#L209](https://github.com/golang/go/blob/f0c623086396faf308fb7e626bf4bf8a5010c857/src/net/sock_posix.go#L209)

**Comment by Natolumin** [comment]
Documenting here a couple issues/gotchas I ran into: 

#### Bindtodevice
 * SO_BINDTODEVICE works in both directions: restricts receiving to only one interface, but also sends eg broadcasts on this interface, instead of using the default route. 
 * On the BSDs, IP_RECVIF only works in the receive direction. For the send direction you apparently are supposed to use BPF.
 * On Darwin, IP_RECVIF works in recv and IP_BOUND_IF works in send. But IP_BOUND_IF is v4-only, and IPV6_BOUND_IF is v6-only (at the IPPROTO_IPV6 optlevel) so that needs to be handled

So, it's complex to force a connection to send its broadcasts / multicasts / link-local unicasts on a specific interface this way. I also think it's not a great idea to force bindtodevice-like semantics; there's no reason we shouldn't be able to use a single socket to listen on all interfaces, and still direct our responses to the correct peer.

There is a portable solution: using [PacketConn.WriteTo](https://godoc.org/golang.org/x/net/ipv6#PacketConn.WriteTo) or [UDPConn.WriteMsgUDP](https://golang.org/pkg/net/#UDPConn.WriteMsgUDP), we can specify in the OOB data what interface to send on on a per-packet basis

This solves the case of the send direction of bindtodevice for the bsds (because we know the interface, it's the one we tried to bind on), but if we want a socket that is not bound to an interface, we need to know the interface we receive a specific request on to decide on what interface to send the response. This requires changing the API of the dhcp library Serve() and handlers to pass this info around, which is a breaking change.

I think the proper solution here is to stop using `dhcpv6.server6` and implement our own server/connection/handler.
I don't think it's a good fit to have the server in the dhcp library (eg. it's the only thing that logs or launches its own goroutines in there). I expect every client has its own specific needs about connection handling, and the interfaces of the handlers.
For example we already have in coredhcp a MainHandler that wraps various handlers with a different api. Serve() only accepts one address at a time, so to handle multiple addresses as in this proposal we would need to call it multiple times. As time goes I expect our needs there will keep evolving, and we shouldn't have to organize with all the downstream users of the dhcp lib for each of these changes.
(@insomniacslk @pmazzini would you be opposed to this; how much ?)

#### Multiple sockets and multicast
Before kernel 4.20 and specifically [commit 15033f0](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=15033f0457dca569b284bef0c8d3ad55fb37eacb), joining a multicast group on a wildcard address is dangerous, as you will receive **all** the groups on the correct port that **any socket on the machine** subscribed to. In this case you'd only run into this if you try to run multiple dhcp servers on the same machine, but still, this is a wild wtf bug

**Comment by insomniacslk** [comment]
Overall it looms very good to me. The only thing I'd like to discuss is whether we should use the same syntax for V6 and v4
