### ISSUE TITLE
No windows support due to 3rd party package restrictions. 

### ISSUE THREAD

**Issue by Mantic** [coredhcp/coredhcp#63]
Trying to compile for windows fails because dependencies to "github.com/u-root/u-root/pkg/rand" (from the locally referenced package: "github.com/insomniacslk/dhcp") does not support any windows builds. It has build constraints on *nix systems only in order to use a crypto-safe random number generator (which there are options for windows). This forces coredhcp to run on *nix systems only. 

I'm developing on a windows machine and intend to deploy to a debian server, so I could really just use docker locally for development. That being said, is this a strictly *nix application? Any reason why it shouldn't be ran on windows? 

Writing this up... I realize this may be more of an insomniacslk/dhcp bug, but it still affects this package too.

**Comment by pmazzini** [comment]
> I realize this may be more of an insomniacslk/dhcp bug

Yes, better to open an issue there.

> Any reason why it shouldn't be ran on windows?

We are happy to accept PRs for adding windows support to the dhcp library.

**Comment by pmazzini** [comment]
Issue was opened on the library:

https://github.com/insomniacslk/dhcp/issues/339
