### ISSUE TITLE
`interface` is a required parameter, but not shown in the example configs

### ISSUE THREAD

**Issue by bradbeam** [coredhcp/coredhcp#79]
coredhcp fails to start without specifying an interface to listen on.

**Comment by skrivy** [comment]
We hit this issue as well. We would like coredhcp to be interface independent as we only listen on unicast address.

**Comment by insomniacslk** [comment]
Thanks for reporting - I will update docs and examples once #58 is merged

**Comment by pmazzini** [comment]
Related to https://github.com/coredhcp/coredhcp/pull/24.

**Comment by Natolumin** [comment]
I think with #58, the example config file in the README is once again correct, this would be fixed. We'll tackle docs update in general in #78
