### ISSUE TITLE
Plugin logging on registration can't be made silent

### ISSUE THREAD

**Issue by elmarco** [coredhcp/coredhcp#86]
Hi,

When the plugins are init(), they log the registration:
```
[2020-02-06T14:47:46+01:00]  INFO plugins: Registering plugin "dns"
[2020-02-06T14:47:46+01:00]  INFO plugins: Registering plugin "file"
...
```

Unfortunately, I can't see a way to silent it, since init() is called early, before the program has the chance to change logrus behaviour. Please advise.

**Comment by elmarco** [comment]
so my current workaround is to have a custom plugin that does:

```
func init() {
	log := logger.GetLogger("plugins")
	log.Logger.SetLevel(logrus.WarnLevel)
}
```

**Comment by insomniacslk** [comment]
Hi @elmarco , the current method to register plugins is suboptimal, and will change. This is tracked in https://github.com/coredhcp/coredhcp/issues/45 and will let you do what you are asking here. It's faily simple to do, and I'll try to tackle it this week

**Comment by insomniacslk** [comment]
for an example of how it will look like, see how we register plugins in another project, https://github.com/facebookincubator/contest/blob/master/cmds/contest/main.go#L90

**Comment by insomniacslk** [comment]
@elmarco can you try with the latest commit? Now setting the log level globally should not print the plugin loading messages anymore.

We can also add a CLI flag for the purpose

**Comment by elmarco** [comment]
works for me, thanks
