### ISSUE TITLE
Change "interface" to optional and let DHCP listens on all interfaces in case of no interface offered

### ISSUE THREAD

**Issue by guo1017138** [coredhcp/coredhcp#94]
Hello,

My use case is pretty simple that I only response the static leases. Which MAC is known by the dhcp server. So, I don't matter which interface the Discover message incoming, but just check the MAC is there and then will reply the DHCP Offer message.
So, I don't need to specify the interface and want to listen on all interface. 

I've tried allow the interface is empty in the config Load(), and it works well. (I tried IPv4)

Could we change code to allow interface optional for this?

**Comment by Natolumin** [comment]
#58 does that, we should merge it fairly soon, when I find time to rebase it

**Comment by guo1017138** [comment]
@Natolumin , Thank you. I will use the new code by then. Closing this one.
